import type { BusOffer } from '@/types/bus';

export const mockBusOffers: Array<BusOffer & { destination: string; origin: string }> = [
  {
    amenities: ['Live tracking', 'Charging point', 'Water bottle'],
    arrivalAt: '2026-09-20T06:15:00+05:30',
    boardingPoint: 'ISBT Sector 43, Chandigarh',
    busType: 'Volvo AC Sleeper (2+1)',
    cancellationPolicy: 'Free cancellation until 12 hours before departure',
    currency: 'INR',
    departureAt: '2026-09-20T01:00:00+05:30',
    destination: 'Delhi',
    droppingPoint: 'Kashmiri Gate ISBT, Delhi',
    id: 'bus-chd-del-himalayan-101',
    operatorName: 'Himalayan Roadways',
    origin: 'Chandigarh',
    pricePerSeat: 1099,
    refundable: true,
    rating: 4.5,
    seatsRemaining: 9,
    source: 'RoadLink Demo Adapter',
    totalPrice: 0,
  },
  {
    amenities: ['Blanket', 'Charging point', 'Reading light'],
    arrivalAt: '2026-09-20T05:45:00+05:30',
    boardingPoint: 'Tribune Chowk, Chandigarh',
    busType: 'Bharat Benz AC Seater (2+2)',
    cancellationPolicy: 'Partial refund until 24 hours before departure',
    currency: 'INR',
    departureAt: '2026-09-20T00:30:00+05:30',
    destination: 'Delhi',
    droppingPoint: 'Majnu Ka Tila, Delhi',
    id: 'bus-chd-del-northern-202',
    operatorName: 'Northern Travels',
    origin: 'Chandigarh',
    pricePerSeat: 849,
    refundable: true,
    rating: 4.2,
    seatsRemaining: 4,
    source: 'BusConnect Demo Adapter',
    totalPrice: 0,
  },
  {
    amenities: ['Live tracking', 'Charging point', 'Wi-Fi'],
    arrivalAt: '2026-09-20T11:15:00+05:30',
    boardingPoint: 'Kashmiri Gate ISBT, Delhi',
    busType: 'Volvo AC Multi-Axle Seater',
    cancellationPolicy: 'Free cancellation until 18 hours before departure',
    currency: 'INR',
    departureAt: '2026-09-20T05:30:00+05:30',
    destination: 'Jaipur',
    droppingPoint: 'Sindhi Camp, Jaipur',
    id: 'bus-del-jai-rajputana-303',
    operatorName: 'Rajputana Express',
    origin: 'Delhi',
    pricePerSeat: 799,
    refundable: true,
    rating: 4.4,
    seatsRemaining: 12,
    source: 'RoadLink Demo Adapter',
    totalPrice: 0,
  },
];
