import type { CarOffer } from '@/types/car';

export const mockCarOffers: Array<CarOffer> = [
  {
    id: 'car-delhi-swift-101',
    providerName: 'Mandyal Drive',
    vehicleName: 'Maruti Suzuki Swift or similar',
    category: 'Economy',
    transmission: 'Manual',
    seats: 5,
    bags: 2,
    fuelPolicy: 'Full to full',
    mileagePolicy: 'Unlimited kilometres',
    cancellationPolicy: 'Free cancellation until 24 hours before pickup',
    features: ['Air conditioning', 'Bluetooth', 'Theft protection'],
    pricePerDay: 2150,
    totalPrice: 0,
    currency: 'INR',
    source: 'DriveConnect Demo Adapter',
    carsRemaining: 4,
    pickupLocation: 'Delhi',
    dropoffLocation: 'Delhi',
    rentalMode: 'self-drive',
  },
  {
    id: 'car-delhi-creta-202',
    providerName: 'RoadTrip Rentals',
    vehicleName: 'Hyundai Creta or similar',
    category: 'SUV',
    transmission: 'Automatic',
    seats: 5,
    bags: 3,
    fuelPolicy: 'Full to full',
    mileagePolicy: '300 kilometres per day',
    cancellationPolicy: 'Free cancellation until 48 hours before pickup',
    features: ['Air conditioning', 'GPS', 'Collision protection'],
    pricePerDay: 3850,
    totalPrice: 0,
    currency: 'INR',
    source: 'RoadTrip Demo Adapter',
    carsRemaining: 2,
    pickupLocation: 'Delhi',
    dropoffLocation: 'Delhi',
    rentalMode: 'self-drive',
  },
  {
    id: 'car-chandigarh-dzire-303',
    providerName: 'Himalayan Wheels',
    vehicleName: 'Maruti Suzuki Dzire or similar',
    category: 'Compact sedan',
    transmission: 'Manual',
    seats: 5,
    bags: 2,
    fuelPolicy: 'Same to same',
    mileagePolicy: 'Unlimited kilometres',
    cancellationPolicy: 'Partial refund until 24 hours before pickup',
    features: ['Air conditioning', 'USB charging', 'Roadside assistance'],
    pricePerDay: 2450,
    totalPrice: 0,
    currency: 'INR',
    source: 'Himalayan Wheels Demo Adapter',
    carsRemaining: 5,
    pickupLocation: 'Chandigarh',
    dropoffLocation: 'Chandigarh',
    rentalMode: 'self-drive',
  },
  {
    id: 'car-delhi-chauffeur-404',
    providerName: 'Mandyal Chauffeur Services',
    vehicleName: 'Toyota Etios or similar',
    category: 'Chauffeur sedan',
    transmission: 'Manual',
    seats: 4,
    bags: 2,
    fuelPolicy: 'Fuel included in stated allowance',
    mileagePolicy: '250 kilometres per day',
    cancellationPolicy: 'Free cancellation until 24 hours before pickup',
    features: ['Professional driver', 'Air conditioning', 'Driver allowance included'],
    pricePerDay: 4200,
    totalPrice: 0,
    currency: 'INR',
    source: 'Mandyal Chauffeur Demo Adapter',
    carsRemaining: 3,
    pickupLocation: 'Delhi',
    dropoffLocation: 'Delhi',
    rentalMode: 'chauffeur',
  },
];
