import type { FlightOffer } from '@/types/flight';

export const mockFlightOffers: FlightOffer[] = [
  {
    baggage: '15 kg check-in + 7 kg cabin',
    cabinClass: 'economy',
    currency: 'INR',
    fareFamily: 'Saver',
    id: 'offer-del-bom-indigo-201',
    pricePerAdult: 5890,
    refundable: false,
    seatsRemaining: 6,
    segments: [
      {
        airlineCode: '6E',
        airlineName: 'IndiGo',
        arrivalAirport: 'BOM',
        arrivalAt: '2026-09-15T09:20:00+05:30',
        departureAirport: 'DEL',
        departureAt: '2026-09-15T07:10:00+05:30',
        durationMinutes: 130,
        flightNumber: '6E 201',
        leg: 'outbound',
        stops: 0,
      },
    ],
    supplier: 'SkyConnect Demo Adapter',
    totalPrice: 0,
  },
  {
    baggage: '20 kg check-in + 7 kg cabin',
    cabinClass: 'economy',
    currency: 'INR',
    fareFamily: 'Flex',
    id: 'offer-del-bom-airindia-887',
    pricePerAdult: 7240,
    refundable: true,
    seatsRemaining: 3,
    segments: [
      {
        airlineCode: 'AI',
        airlineName: 'Air India',
        arrivalAirport: 'BOM',
        arrivalAt: '2026-09-15T12:40:00+05:30',
        departureAirport: 'DEL',
        departureAt: '2026-09-15T10:25:00+05:30',
        durationMinutes: 135,
        flightNumber: 'AI 887',
        leg: 'outbound',
        stops: 0,
      },
    ],
    supplier: 'National Air Demo Adapter',
    totalPrice: 0,
  },
  {
    baggage: '15 kg check-in + 7 kg cabin',
    cabinClass: 'economy',
    currency: 'INR',
    fareFamily: 'Value',
    id: 'offer-del-blr-akasa-1221',
    pricePerAdult: 6410,
    refundable: false,
    seatsRemaining: 8,
    segments: [
      {
        airlineCode: 'QP',
        airlineName: 'Akasa Air',
        arrivalAirport: 'BLR',
        arrivalAt: '2026-09-15T10:05:00+05:30',
        departureAirport: 'DEL',
        departureAt: '2026-09-15T07:15:00+05:30',
        durationMinutes: 170,
        flightNumber: 'QP 1221',
        leg: 'outbound',
        stops: 0,
      },
    ],
    supplier: 'SkyConnect Demo Adapter',
    totalPrice: 0,
  },
  {
    baggage: '20 kg check-in + 7 kg cabin',
    cabinClass: 'economy',
    currency: 'INR',
    fareFamily: 'Return Flex',
    id: 'offer-del-bom-airindia-return-887',
    pricePerAdult: 13980,
    refundable: true,
    seatsRemaining: 3,
    segments: [
      {
        airlineCode: 'AI',
        airlineName: 'Air India',
        arrivalAirport: 'BOM',
        arrivalAt: '2026-09-15T12:40:00+05:30',
        departureAirport: 'DEL',
        departureAt: '2026-09-15T10:25:00+05:30',
        durationMinutes: 135,
        flightNumber: 'AI 887',
        leg: 'outbound',
        stops: 0,
      },
      {
        airlineCode: 'AI',
        airlineName: 'Air India',
        arrivalAirport: 'DEL',
        arrivalAt: '2026-09-18T20:05:00+05:30',
        departureAirport: 'BOM',
        departureAt: '2026-09-18T17:55:00+05:30',
        durationMinutes: 130,
        flightNumber: 'AI 805',
        leg: 'return',
        stops: 0,
      },
    ],
    supplier: 'National Air Demo Adapter',
    totalPrice: 0,
  },
];
