export const HOTEL_FIXED_ASSET_CATEGORIES = [
  'FURNITURE',
  'EQUIPMENT',
  'ELECTRICAL',
  'IT',
  'VEHICLE',
  'BUILDING_SYSTEM',
] as const;

export const HOTEL_FIXED_ASSET_EVENTS = ['VERIFIED', 'MOVED'] as const;
