export const HOTEL_VENDOR_CATEGORIES = [
  'FOOD_AND_BEVERAGE',
  'HOUSEKEEPING',
  'LAUNDRY',
  'MAINTENANCE',
  'TECHNOLOGY',
  'TRANSPORT',
  'OTHER',
] as const;

export const HOTEL_VENDOR_STATUSES = ['ACTIVE', 'PAUSED'] as const;
