ALTER TABLE "HotelQuote" ADD COLUMN "hotelSlug" TEXT NOT NULL DEFAULT '';
ALTER TABLE "HotelQuote" ADD COLUMN "checkInDate" TEXT NOT NULL DEFAULT '';
ALTER TABLE "HotelQuote" ADD COLUMN "checkOutDate" TEXT NOT NULL DEFAULT '';
ALTER TABLE "HotelQuote" ADD COLUMN "ratePlanId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "HotelQuote" ADD COLUMN "rooms" INTEGER NOT NULL DEFAULT 1;
