-- The PostgreSQL baseline was generated after marketplace tax governance was
-- added, so it already contains this complete schema and the 2000 basis-point
-- commission default. Keep this migration as a recorded no-op for history
-- parity instead of attempting to create the same objects twice.
