-- The PostgreSQL baseline was generated after partner KYC governance was added,
-- so it already contains this complete schema. Keep this migration as a recorded no-op
-- for history parity instead of attempting to create the same objects twice.
