import type { Metadata } from 'next';
import Link from 'next/link';
import { redirect } from 'next/navigation';

import { Card } from '@/components/ui/Card';
import { getPartnerAccess } from '@/lib/partnerAuth';
import { accountingAccountLabel } from '@/lib/pms/accountingLedger';
import { getPartnerAccountingLedger } from '@/services/partnerAccountingLedgerService';

export const metadata: Metadata = { title: 'Accounting and ledgers | Mandyal PMS' };

function money(amount: number, currency: string) {
  return new Intl.NumberFormat('en-IN', {
    currency,
    maximumFractionDigits: 0,
    style: 'currency',
  }).format(amount);
}

export default async function PartnerAccountingPage() {
  const access = await getPartnerAccess();
  if (!access?.partnerId || access.partnerType !== 'HOTEL') redirect('/partner');
  if (access.memberRole !== 'ADMIN') {
    return (
      <main className="booking-page">
        <div className="booking-page__container">
          <Card>
            <h1>Administrator access required</h1>
            <p>Supplier-wide journal balances are restricted to hotel administrators.</p>
            <Link className="ui-button ui-button--secondary" href="/partner/pms">
              Return to PMS dashboard
            </Link>
          </Card>
        </div>
      </main>
    );
  }
  const ledger = await getPartnerAccountingLedger(access.partnerId);

  return (
    <main className="booking-page">
      <div className="booking-page__container">
        <header className="partner-page__heading">
          <div>
            <p className="hotel-page__eyebrow">Finance · immutable double-entry evidence</p>
            <h1>Accounting and ledgers</h1>
            <p className="booking-page__intro">
              Review supplier-attributed payment and refund journals. Entries are generated by
              governed financial events and cannot be edited from the PMS.
            </p>
          </div>
          <div className="manage-booking__document-actions">
            <Link className="ui-button ui-button--secondary" href="/partner/pms/billing">
              Guest folios
            </Link>
            <Link className="ui-button ui-button--secondary" href="/partner/pms/gst-billing">
              GST preparation
            </Link>
            <Link className="ui-button ui-button--secondary" href="/partner/settlements">
              Settlements
            </Link>
          </div>
        </header>

        {ledger.safetyLimitReached || ledger.currencyConflict || !ledger.balanced ? (
          <p className="booking-page__payment-error" role="alert">
            {ledger.safetyLimitReached
              ? 'The posting safety limit was reached. Totals are withheld; use a narrower governed export.'
              : ledger.currencyConflict
                ? 'Multiple currencies are present. Totals are withheld until the journals are reviewed separately by currency.'
                : 'The displayed postings are not balanced. Totals are withheld pending finance review.'}
          </p>
        ) : null}

        <div className="partner-bookings__summary">
          <Card>
            <span>Journals represented</span>
            <strong>{ledger.journalCount}</strong>
            <small>Supplier-attributed payment and refund events</small>
          </Card>
          <Card>
            <span>Debit postings</span>
            <strong>
              {!ledger.safetyLimitReached && !ledger.currencyConflict && ledger.balanced
                ? money(ledger.totalDebit, ledger.currency)
                : 'Withheld'}
            </strong>
          </Card>
          <Card>
            <span>Credit postings</span>
            <strong>
              {!ledger.safetyLimitReached && !ledger.currencyConflict && ledger.balanced
                ? money(ledger.totalCredit, ledger.currency)
                : 'Withheld'}
            </strong>
          </Card>
          <Card>
            <span>Control status</span>
            <strong>{ledger.balanced ? 'Balanced' : 'Review required'}</strong>
            <small>Debit and credit equality</small>
          </Card>
        </div>

        <Card>
          <p className="hotel-page__eyebrow">Account summary</p>
          <h2>Supplier posting balances</h2>
          {ledger.accounts.length ? (
            <div className="pms-room-rack__table-wrap">
              <table className="pms-room-rack__table">
                <thead>
                  <tr>
                    <th scope="col">Account</th>
                    <th scope="col">Debit</th>
                    <th scope="col">Credit</th>
                  </tr>
                </thead>
                <tbody>
                  {ledger.accounts.map((account) => (
                    <tr key={account.accountCode}>
                      <th scope="row">{accountingAccountLabel(account.accountCode)}</th>
                      <td>{money(account.debit, ledger.currency)}</td>
                      <td>{money(account.credit, ledger.currency)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <p>No supplier-attributed financial journals have been posted.</p>
          )}
        </Card>

        <Card>
          <p className="hotel-page__eyebrow">Day book</p>
          <h2>Recent immutable postings</h2>
          {ledger.postings.length ? (
            <div className="pms-room-rack__table-wrap">
              <table className="pms-room-rack__table">
                <thead>
                  <tr>
                    <th scope="col">Posted</th>
                    <th scope="col">Private journal</th>
                    <th scope="col">Source</th>
                    <th scope="col">Account</th>
                    <th scope="col">Direction</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Control</th>
                  </tr>
                </thead>
                <tbody>
                  {ledger.postings.map((posting, index) => (
                    <tr key={`${posting.journalReference}-${posting.accountCode}-${index}`}>
                      <td>{posting.createdAt.toISOString().slice(0, 10)}</td>
                      <td>{posting.journalReference.toUpperCase()}</td>
                      <td>{posting.sourceType.toLowerCase().replaceAll('_', ' ')}</td>
                      <td>{accountingAccountLabel(posting.accountCode)}</td>
                      <td>{posting.direction.toLowerCase()}</td>
                      <td>{money(posting.amount, posting.currency)}</td>
                      <td>
                        {posting.status === 'POSTED' && posting.journalBalanced
                          ? 'Posted · balanced'
                          : 'Review required'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <p>No accounting postings are available yet.</p>
          )}
        </Card>

        <Card>
          <p className="hotel-page__eyebrow">Scope boundary</p>
          <p>
            This ledger covers system-generated marketplace payments and refunds attributed to this
            supplier. Manual expenses, statutory books, bank reconciliation, and tax filing require
            an approved accounting process or external accounting integration and are not inferred
            from operational PMS data.
          </p>
        </Card>
      </div>
    </main>
  );
}
